apiVersion: v1
kind: Service
metadata:
  name: coforma-studio-api
  namespace: coforma-studio
spec:
  type: ClusterIP
  selector:
    app: coforma-studio-api
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
