apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coforma-studio
resources:
- namespace.yaml
- web-deployment.yaml
- web-service.yaml
- network-policies.yaml
images:
- digest: sha256:32c49ba32529da5cbfe8785e1ddd3dadefbe11de2fc50bd407595e9de63eb7de
  name: ghcr.io/madfam-org/coforma-studio/web
  newName: ghcr.io/madfam-org/coforma-studio/web
