apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coforma-studio
resources:
- namespace.yaml
- web-deployment.yaml
- web-service.yaml
- network-policies.yaml
images:
- digest: sha256:cae99dd7053a64df77822f6ae7aa822e232feda1ca477e932814ae5d6be93cd1
  name: ghcr.io/madfam-org/coforma-studio/web
  newName: ghcr.io/madfam-org/coforma-studio/web
