apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coforma-studio
resources:
- namespace.yaml
- web-deployment.yaml
- web-service.yaml
- network-policies.yaml
images:
- digest: sha256:449f55f9dde8acc370530fa9cf8cab08eadde426a11453461adeedebdfe32ffd
  name: ghcr.io/madfam-org/coforma-studio/web
  newName: ghcr.io/madfam-org/coforma-studio/web
